services:
  web:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - tg-net

  bot:
    build: .
    command: python bot.py
    env_file:
      - .env
    depends_on:
      - web
    networks:
      - tg-net

networks:
  tg-net:
    driver: bridge